default_stages: [pre-commit]
exclude: "research/plant_science_research/."

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        exclude: '\.json$'
        stages: [pre-commit]
      # - id: name-tests-test
      #   stages: [pre-commit]
      - id: check-added-large-files
        stages: [pre-commit]
        args:
          - "--maxkb=15000"
